name: lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6.0.2
    - name: setupBun
      uses: oven-sh/setup-bun@v2.2.0
    - name: install
      run: bun install --frozen-lockfile
    - name: eslint
      run: bunx --bun eslint .
